#!/bin/bash

echo "======================================"
echo "Session Cookie Fix Applied!"
echo "======================================"
echo ""
echo "IMPORTANT: You need to RESTART the frontend server for the proxy to take effect."
echo ""
echo "Changes made:"
echo "  ✅ Added Vite proxy configuration (vite.config.ts)"
echo "  ✅ Changed API_BASE_URL from 'http://127.0.0.1:8000/api' to '/api'"
echo "  ✅ Removed manual cookie setting from login view"
echo "  ✅ Enhanced debug logging in current_user view"
echo ""
echo "------------------------------------"
echo "How the fix works:"
echo "------------------------------------"
echo ""
echo "BEFORE (Cross-Origin - Cookies blocked):"
echo "  Frontend: http://localhost:5173"
echo "  Backend:  http://127.0.0.1:8000"
echo "  → Different origins → SameSite=Lax blocks cookies"
echo ""
echo "AFTER (Same-Origin via Proxy):"
echo "  Frontend: http://localhost:5173"
echo "  API calls: http://localhost:5173/api → Proxied to → http://127.0.0.1:8000/api"
echo "  → Same origin → Cookies work! ✅"
echo ""
echo "------------------------------------"
echo "Steps to test:"
echo "------------------------------------"
echo ""
echo "1. Stop the frontend server (Ctrl+C in Terminal 2)"
echo ""
echo "2. Restart frontend:"
echo "   cd /home/badr/book-generator/frontend"
echo "   npm run dev"
echo ""
echo "3. Clear browser cookies:"
echo "   - Open DevTools (F12)"
echo "   - Go to Application tab"
echo "   - Clear cookies for localhost"
echo ""
echo "4. Test sign in:"
echo "   - Go to http://localhost:5173/auth/signin"
echo "   - Sign in with test5 credentials"
echo "   - Should see successful login and redirect to /profile"
echo ""
echo "5. Verify session:"
echo "   - Check Network tab: POST /api/auth/login/ should show Set-Cookie header"
echo "   - Check Application tab: sessionid cookie should be present"
echo "   - Refresh page: GET /api/auth/me/ should return 200 (not 403)"
echo "   - Console should be clean (no errors)"
echo ""
echo "------------------------------------"
echo "Debug checklist:"
echo "------------------------------------"
echo ""
echo "Backend logs should show:"
echo "  ✅ Login successful for user: test5"
echo "  ✅ Session key: [some-key]"
echo "  ✅ GET /api/auth/me/ returns 200 (not 403)"
echo ""
echo "Browser DevTools should show:"
echo "  ✅ No CORS errors"
echo "  ✅ sessionid cookie in Application tab"
echo "  ✅ Cookie sent with /api/auth/me/ request"
echo ""
echo "======================================"
