#!/bin/bash

echo "======================================"
echo "Testing Book Creation Feature"
echo "======================================"
echo ""

# Check frontend server status
echo "1. Checking frontend setup..."
if [ -f "/home/badr/book-generator/frontend/vite.config.ts" ]; then
    if grep -q "proxy" /home/badr/book-generator/frontend/vite.config.ts; then
        echo "   ✅ Vite proxy configured"
    else
        echo "   ❌ Vite proxy missing"
    fi
fi

if [ -f "/home/badr/book-generator/frontend/src/views/Books/CreateGuided.vue" ]; then
    echo "   ✅ CreateGuided.vue exists"
else
    echo "   ❌ CreateGuided.vue missing"
fi

if [ -f "/home/badr/book-generator/frontend/src/views/Profile.vue" ]; then
    echo "   ✅ Profile.vue exists"
else
    echo "   ❌ Profile.vue missing"
fi

echo ""
echo "2. Checking router configuration..."
if grep -q "CreateGuided" /home/badr/book-generator/frontend/src/router/index.ts; then
    echo "   ✅ CreateGuided route configured"
else
    echo "   ❌ CreateGuided route missing"
fi

echo ""
echo "======================================"
echo "Manual Testing Steps"
echo "======================================"
echo ""
echo "STEP 1: Ensure servers are running"
echo "   Terminal 1 (Backend):"
echo "   $ cd /home/badr/book-generator/backend"
echo "   $ source venv/bin/activate"
echo "   $ python manage.py runserver"
echo ""
echo "   Terminal 2 (Frontend - MUST RESTART!):"
echo "   $ cd /home/badr/book-generator/frontend"
echo "   $ npm run dev"
echo ""
echo "STEP 2: Clear browser cache & cookies"
echo "   - Press F12 (DevTools)"
echo "   - Go to Application tab"
echo "   - Clear all cookies for localhost"
echo "   - Refresh page (Ctrl+Shift+R)"
echo ""
echo "STEP 3: Test Sign In"
echo "   - Go to: http://localhost:5173/auth/signin"
echo "   - Sign in with: test5 / [your-password]"
echo "   - Should redirect to: http://localhost:5173/profile"
echo "   - Check console for errors (should be clean)"
echo ""
echo "STEP 4: Test Profile Dashboard"
echo "   - Should see sidebar with navigation"
echo "   - Should see 'Start Creating Your First Book!' section"
echo "   - Should see 4-step quick guide"
echo "   - Click 'Create Your First Book' button"
echo ""
echo "STEP 5: Test Book Creation Wizard"
echo "   - Should redirect to: http://localhost:5173/profile/create"
echo "   - Should see 4-step progress indicator"
echo ""
echo "   Step 1 - Choose Domain:"
echo "   - Select 'Meditation & Mindfulness'"
echo "   - Click 'Next Step'"
echo ""
echo "   Step 2 - Choose Sub-Niche:"
echo "   - Should see 3 meditation niches"
echo "   - Select 'Sleep Meditation Stories'"
echo "   - Click 'Next Step'"
echo ""
echo "   Step 3 - Choose Page Length:"
echo "   - Select '20 pages'"
echo "   - Should see estimated time: 8-13 min"
echo "   - Click 'Next Step'"
echo ""
echo "   Step 4 - Review & Confirm:"
echo "   - Should see summary of selections"
echo "   - Click 'Generate My Book'"
echo "   - Should show loading state"
echo "   - Should redirect to book details page"
echo ""
echo "======================================"
echo "Expected Results"
echo "======================================"
echo ""
echo "✅ No console errors"
echo "✅ Smooth navigation between steps"
echo "✅ Visual feedback on selections"
echo "✅ Progress indicator updates"
echo "✅ Form validation prevents invalid submissions"
echo "✅ Loading states during submission"
echo "✅ Successful redirect after book creation"
echo ""
echo "======================================"
echo "Troubleshooting"
echo "======================================"
echo ""
echo "Issue: 403 Forbidden errors"
echo "Fix: Restart frontend server (proxy config)"
echo ""
echo "Issue: Router warnings about /auth/me"
echo "Fix: Already fixed, clear cache"
echo ""
echo "Issue: Styles not loading"
echo "Fix: Restart frontend server"
echo ""
echo "Issue: API calls failing"
echo "Fix: Check both servers are running"
echo ""
echo "======================================"
echo "Need help? Check these docs:"
echo "  - QUICK_FIX.md (Session/Auth issues)"
echo "  - BOOK_CREATION_FEATURE.md (Feature details)"
echo "  - ROUTE_STRUCTURE.md (Routes reference)"
echo "======================================"
