# Generated by Django 4.2.7 on 2025-10-23 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tone', models.CharField(choices=[('educational', 'Educational'), ('inspirational', 'Inspirational'), ('technical', 'Technical'), ('playful', 'Playful'), ('professional', 'Professional'), ('conversational', 'Conversational')], max_length=20)),
                ('target_audience', models.CharField(choices=[('kids', 'Kids (5-12 years)'), ('parents', 'Parents'), ('students', 'Students'), ('professionals', 'Professionals'), ('entrepreneurs', 'Entrepreneurs'), ('general', 'General Public')], max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese')], default='en', max_length=2)),
                ('length', models.CharField(choices=[('short', 'Short (15-20 pages)'), ('medium', 'Medium (20-25 pages)'), ('full', 'Full (25-30 pages)')], default='medium', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CoverStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('style', models.CharField(choices=[('minimalist', 'Minimalist'), ('futuristic', 'Futuristic'), ('playful', 'Playful'), ('elegant', 'Elegant'), ('corporate', 'Corporate'), ('artistic', 'Artistic')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='cover_styles/')),
                ('color_scheme', models.JSONField(default=dict, help_text='Primary and accent colors')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('audience', models.CharField(blank=True, help_text='Target audience description', max_length=200)),
                ('market_size', models.CharField(blank=True, help_text='Market size info', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niches', to='books.domain')),
            ],
            options={
                'ordering': ['domain', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BookTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('title_template', models.CharField(help_text='Template for generating title', max_length=200)),
                ('outline', models.TextField(help_text='Template book outline')),
                ('style_guide', models.TextField(blank=True, help_text='Writing style guidelines', null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='books.domain')),
                ('niche', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='books.niche')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating Content'), ('content_generated', 'Content Generated'), ('cover_pending', 'Awaiting Cover Selection'), ('ready', 'Ready for Download'), ('error', 'Generation Error')], default='draft', max_length=20)),
                ('mongodb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_to_generate', models.DecimalField(decimal_places=2, default=0, help_text='Cost to generate this book', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency for this book', max_length=3)),
                ('generation_time_seconds', models.IntegerField(default=0)),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_commercial', models.BooleanField(default=False)),
                ('commercial_license_type', models.CharField(blank=True, choices=[('personal', 'Personal Use Only'), ('commercial', 'Commercial Use'), ('resell', 'Resell Rights')], max_length=50, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_generated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('book_style', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.bookstyle')),
                ('cover_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.coverstyle')),
                ('domain', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.domain')),
                ('niche', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.niche')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
