# Generated by Django 4.2.7 on 2025-10-16 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('domain', models.CharField(choices=[('health', 'Health & Wellness'), ('food', 'Food & Nutrition'), ('personal_dev', 'Personal Development'), ('hobbies', 'Hobbies & Crafts'), ('lifestyle', 'Lifestyle')], max_length=50)),
                ('sub_niche', models.CharField(choices=[('yoga_beginners', 'Yoga for Beginners'), ('home_workouts', 'Home Workouts'), ('mental_wellness', 'Mental Wellness'), ('vegan_recipes', 'Vegan Recipes'), ('meal_prep', 'Meal Prep Guide'), ('smoothie_recipes', 'Smoothie Recipes'), ('productivity', 'Productivity Hacks'), ('morning_routines', 'Morning Routines'), ('goal_setting', 'Goal Setting'), ('gardening', 'Home Gardening'), ('photography', 'Photography Basics'), ('diy_crafts', 'DIY Crafts'), ('minimalism', 'Minimalist Living'), ('sustainable_living', 'Sustainable Living'), ('travel_hacks', 'Travel Hacks')], max_length=50)),
                ('page_length', models.IntegerField(choices=[(15, '15 Pages'), (20, '20 Pages'), (25, '25 Pages'), (30, '30 Pages')])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating Content'), ('content_generated', 'Content Generated'), ('cover_pending', 'Awaiting Cover Selection'), ('ready', 'Ready for Download'), ('error', 'Generation Error')], default='draft', max_length=20)),
                ('mongodb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_generated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='books_book_user_id_3df9b7_idx'), models.Index(fields=['status'], name='books_book_status_ea5e47_idx')],
            },
        ),
    ]
