# Generated by Django 4.2.7 on 2025-10-23 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='users.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='niche',
            unique_together={('domain', 'slug')},
        ),
        migrations.AddIndex(
            model_name='booktemplate',
            index=models.Index(fields=['user', '-created_at'], name='books_bookt_user_id_ddf451_idx'),
        ),
        migrations.AddIndex(
            model_name='booktemplate',
            index=models.Index(fields=['domain'], name='books_bookt_domain__fa522c_idx'),
        ),
        migrations.AddIndex(
            model_name='booktemplate',
            index=models.Index(fields=['is_public'], name='books_bookt_is_publ_8e8d20_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['user', '-created_at'], name='books_book_user_id_3df9b7_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status'], name='books_book_status_ea5e47_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['domain'], name='books_book_domain__0e9637_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['subscription_plan'], name='books_book_subscri_fcd939_idx'),
        ),
    ]
