# Generated by Django 4.2.7 on 2025-10-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='domain',
            field=models.CharField(choices=[('language_kids', 'Language and Kids'), ('tech_ai', 'Technology and AI'), ('nutrition', 'Nutrition and Wellness'), ('meditation', 'Meditation'), ('home_workout', 'Home Workout')], max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='sub_niche',
            field=models.CharField(choices=[('ai_learning_stories', 'AI-Powered Personalized Learning Stories'), ('multilingual_coloring', 'Multilingual Coloring Books'), ('kids_mindful_journals', "Kids' Mindful Activity Journals"), ('ai_ethics', 'AI Ethics and Future Trends'), ('nocode_guides', 'No-Code/Low-Code Development Guides'), ('smart_home_diy', 'DIY Smart Home and Automation'), ('specialty_diet', 'Specialty Diet Cookbooks'), ('plant_based_cooking', 'Plant-Based Cooking for Beginners'), ('nutrition_mental_health', 'Nutrition for Mental Health'), ('mindfulness_anxiety', 'Mindfulness and Anxiety Workbooks'), ('sleep_meditation', 'Sleep Meditation Stories'), ('gratitude_journals', 'Daily Gratitude Journals with Prompts'), ('equipment_free', 'Equipment-Free Workout Plans'), ('yoga_remote_workers', 'Yoga and Stretching for Remote Workers'), ('mobility_training', "Beginner's Mobility Training")], max_length=50),
        ),
    ]
