# Generated by Django 4.2.7 on 2025-10-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='current_step',
            field=models.CharField(blank=True, help_text='Current generation step', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Generation progress 0-100'),
        ),
    ]
