# Generated by Django 4.2.7 on 2025-10-27 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_current_step_book_progress_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('clean_sans', 'Clean Sans-Serif'), ('elegant_serif', 'Elegant Serif'), ('hand_written', 'Hand-Written/Script'), ('modern_geometric', 'Modern Geometric'), ('classic_traditional', 'Classic Traditional')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('header_font', models.CharField(default='Inter', help_text="Google Font name for headers (e.g., 'Inter', 'Playfair Display')", max_length=100)),
                ('body_font', models.CharField(default='Lato', help_text="Google Font name for body text (e.g., 'Lato', 'Source Serif Pro')", max_length=100)),
                ('header_weight', models.IntegerField(default=700, help_text='Font weight for headers (400=normal, 700=bold, 900=black)')),
                ('body_weight', models.IntegerField(default=400, help_text='Font weight for body text (400=normal, 600=semi-bold)')),
                ('ai_brief_keywords', models.JSONField(default=list, help_text="Keywords in cover brief that trigger this font theme (e.g., ['modern', 'tech', 'minimal'])")),
                ('google_fonts_url', models.TextField(blank=True, help_text='Auto-generated Google Fonts CSS2 API URL')),
                ('priority', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use as default when no domain or AI match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(blank=True, help_text='If set, this font theme is default for this domain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='font_themes', to='books.domain')),
            ],
            options={
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['domain', 'is_active'], name='books_fontt_domain__6bc759_idx'), models.Index(fields=['category'], name='books_fontt_categor_a150e7_idx'), models.Index(fields=['is_default'], name='books_fontt_is_defa_ad7e02_idx')],
            },
        ),
    ]
