# Generated by Django 4.2.7 on 2025-10-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_add_font_theme_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quality_score',
            field=models.IntegerField(default=0, help_text='Automated content quality score (0-100)'),
        ),
    ]
