# Generated by Django 4.2.7 on 2025-10-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_domain_alter_book_sub_niche_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='domain',
            field=models.CharField(choices=[('ai_digital_transformation', 'AI & Digital Transformation'), ('sustainability_green_tech', 'Sustainability & Green Tech'), ('mental_health_tech', 'Mental Health Technology'), ('future_skills', 'Future Skills & Digital Economy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='sub_niche',
            field=models.CharField(choices=[('ai_business_automation', 'AI-Powered Business Automation'), ('machine_learning_basics', 'Machine Learning for Non-Technical Professionals'), ('digital_transformation_strategy', 'Digital Transformation Strategy'), ('ai_ethics_governance', 'AI Ethics and Responsible AI Governance'), ('chatgpt_productivity', 'ChatGPT and AI Tools for Productivity'), ('data_driven_decisions', 'Data-Driven Decision Making'), ('ai_content_creation', 'AI-Powered Content Creation'), ('automation_workflows', 'Building Automation Workflows'), ('renewable_energy_solutions', 'Renewable Energy Solutions for Homes'), ('circular_economy_principles', 'Circular Economy and Sustainable Business'), ('green_technology_innovations', 'Green Technology Innovations'), ('carbon_neutral_living', 'Carbon Neutral Living Guide'), ('sustainable_supply_chain', 'Building Sustainable Supply Chains'), ('eco_friendly_investing', 'Eco-Friendly Investing Strategies'), ('green_building_design', 'Green Building and Architecture'), ('climate_tech_startups', 'Climate Tech Startups and Innovation'), ('ai_mental_health_apps', 'AI-Powered Mental Health Applications'), ('digital_wellness_tools', 'Digital Wellness and Mindfulness Tech'), ('teletherapy_platforms', 'Teletherapy and Online Counseling'), ('mental_health_ai_diagnostics', 'AI Diagnostics for Mental Health'), ('stress_management_apps', 'Stress Management Mobile Applications'), ('cognitive_behavioral_tech', 'Technology in Cognitive Behavioral Therapy'), ('mental_health_wearables', 'Mental Health Wearables and Biofeedback'), ('workplace_mental_health_tech', 'Workplace Mental Health Technology Solutions'), ('remote_work_mastery', 'Remote Work Mastery and Digital Nomad Skills'), ('blockchain_cryptocurrency', 'Blockchain and Cryptocurrency Fundamentals'), ('metaverse_virtual_reality', 'Metaverse and Virtual Reality Skills'), ('cybersecurity_essentials', 'Cybersecurity Essentials for Everyone'), ('digital_entrepreneurship', 'Digital Entrepreneurship in the 2020s'), ('quantum_computing_basics', 'Quantum Computing for Business Leaders'), ('iot_smart_homes', 'IoT and Smart Home Technology'), ('nft_digital_assets', 'NFTs and Digital Asset Management')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booktemplate',
            name='domain',
            field=models.CharField(choices=[('ai_digital_transformation', 'AI & Digital Transformation'), ('sustainability_green_tech', 'Sustainability & Green Tech'), ('mental_health_tech', 'Mental Health Technology'), ('future_skills', 'Future Skills & Digital Economy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booktemplate',
            name='sub_niche',
            field=models.CharField(choices=[('ai_business_automation', 'AI-Powered Business Automation'), ('machine_learning_basics', 'Machine Learning for Non-Technical Professionals'), ('digital_transformation_strategy', 'Digital Transformation Strategy'), ('ai_ethics_governance', 'AI Ethics and Responsible AI Governance'), ('chatgpt_productivity', 'ChatGPT and AI Tools for Productivity'), ('data_driven_decisions', 'Data-Driven Decision Making'), ('ai_content_creation', 'AI-Powered Content Creation'), ('automation_workflows', 'Building Automation Workflows'), ('renewable_energy_solutions', 'Renewable Energy Solutions for Homes'), ('circular_economy_principles', 'Circular Economy and Sustainable Business'), ('green_technology_innovations', 'Green Technology Innovations'), ('carbon_neutral_living', 'Carbon Neutral Living Guide'), ('sustainable_supply_chain', 'Building Sustainable Supply Chains'), ('eco_friendly_investing', 'Eco-Friendly Investing Strategies'), ('green_building_design', 'Green Building and Architecture'), ('climate_tech_startups', 'Climate Tech Startups and Innovation'), ('ai_mental_health_apps', 'AI-Powered Mental Health Applications'), ('digital_wellness_tools', 'Digital Wellness and Mindfulness Tech'), ('teletherapy_platforms', 'Teletherapy and Online Counseling'), ('mental_health_ai_diagnostics', 'AI Diagnostics for Mental Health'), ('stress_management_apps', 'Stress Management Mobile Applications'), ('cognitive_behavioral_tech', 'Technology in Cognitive Behavioral Therapy'), ('mental_health_wearables', 'Mental Health Wearables and Biofeedback'), ('workplace_mental_health_tech', 'Workplace Mental Health Technology Solutions'), ('remote_work_mastery', 'Remote Work Mastery and Digital Nomad Skills'), ('blockchain_cryptocurrency', 'Blockchain and Cryptocurrency Fundamentals'), ('metaverse_virtual_reality', 'Metaverse and Virtual Reality Skills'), ('cybersecurity_essentials', 'Cybersecurity Essentials for Everyone'), ('digital_entrepreneurship', 'Digital Entrepreneurship in the 2020s'), ('quantum_computing_basics', 'Quantum Computing for Business Leaders'), ('iot_smart_homes', 'IoT and Smart Home Technology'), ('nft_digital_assets', 'NFTs and Digital Asset Management')], max_length=50),
        ),
    ]
