// Font Awesome configuration
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// Import specific icons
import {
  faBook,
  faUser,
  faHome,
  faCog,
  faSignOutAlt,
  faSignInAlt,
  faUserPlus,
  faPlus,
  faEdit,
  faTrash,
  faDownload,
  faEye,
  faCheck,
  faSpinner,
  faExclamationTriangle,
  faCalendar,
  faChartLine,
  faStar,
  faUpload,
  faFileAlt,
  faImage,
  faPalette,
  faSave,
  faArrowLeft,
  faArrowRight,
  faTimes,
  faSearch,
  faFilter,
  faBars,
  faEllipsisV,
  faInfoCircle,
  faQuestionCircle,
  faHeart,
  faShare,
  faCopy,
  faExternalLinkAlt,
  faUserCircle,
  faCrown,
  faGem,
  faCreditCard,
  faShoppingCart,
  faChartBar,
  faCalendarAlt,
  faGift,
  faHandshake,
  faPhone,
  faEnvelope,
  faGlobe,
  faMobile,
  faDesktop,
  faTablet,
  faWifi,
  faCloud,
  faDatabase,
  faCode,
  faTerminal,
  faBug,
  faRocket,
  faLightbulb,
  faMagic,
  faPaintBrush
} from '@fortawesome/free-solid-svg-icons'

import {
  faHeart as farHeart,
  faBookmark as farBookmark,
  faFile as farFile,
  faUser as farUser,
  faCalendar as farCalendar,
  faClock as farClock,
  faComment as farComment
} from '@fortawesome/free-regular-svg-icons'

import {
  faGithub,
  faTwitter,
  faLinkedin,
  faGoogle,
  faFacebook,
  faInstagram,
  faYoutube,
  faDiscord,
  faSlack,
  faTelegram,
  faWhatsapp,
  faPaypal,
  faStripe,
  faApple,
  faMicrosoft,
  faAmazon
} from '@fortawesome/free-brands-svg-icons'

// Add icons to the library
library.add(
  // Solid icons
  faBook,
  faUser,
  faHome,
  faCog,
  faSignOutAlt,
  faSignInAlt,
  faUserPlus,
  faPlus,
  faEdit,
  faTrash,
  faDownload,
  faEye,
  faCheck,
  faSpinner,
  faExclamationTriangle,
  faCalendar,
  faChartLine,
  faStar,
  faUpload,
  faFileAlt,
  faImage,
  faPalette,
  faSave,
  faArrowLeft,
  faArrowRight,
  faTimes,
  faSearch,
  faFilter,
  faBars,
  faEllipsisV,
  faInfoCircle,
  faQuestionCircle,
  faHeart,
  faShare,
  faCopy,
  faExternalLinkAlt,
  faUserCircle,
  faCrown,
  faGem,
  faCreditCard,
  faShoppingCart,
  faChartBar,
  faCalendarAlt,
  faGift,
  faHandshake,
  faPhone,
  faEnvelope,
  faGlobe,
  faMobile,
  faDesktop,
  faTablet,
  faWifi,
  faCloud,
  faDatabase,
  faCode,
  faTerminal,
  faBug,
  faRocket,
  faLightbulb,
  faMagic,
  faPaintBrush,

  // Regular icons
  farHeart,
  farBookmark,
  farFile,
  farUser,
  farCalendar,
  farClock,
  farComment,

  // Brand icons
  faGithub,
  faTwitter,
  faLinkedin,
  faGoogle,
  faFacebook,
  faInstagram,
  faYoutube,
  faDiscord,
  faSlack,
  faTelegram,
  faWhatsapp,
  faPaypal,
  faStripe,
  faApple,
  faMicrosoft,
  faAmazon
)

export default FontAwesomeIcon