# Generated by Django 4.2.7 on 2025-10-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='books_per_month',
            new_name='books_per_day',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='books_used_this_month',
            new_name='books_used_today',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='monthly_reset_date',
            new_name='daily_reset_date',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic - $15/month - 1 book/day'), ('premium', 'Premium - $45/month - 3 books/day'), ('enterprise', 'Enterprise - $60/month - 5 books/day')], default='free', max_length=20),
        ),
    ]
