# Generated by Django 4.2.7 on 2025-10-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('parents', 'For Parents'), ('creators', 'For Creators'), ('testing', 'Testing (Unlimited)')], default='free', max_length=20),
        ),
    ]
