# Generated by Django 4.2.7 on 2025-10-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_books_per_month_userprofile_books_per_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='books_used_today',
            new_name='books_used_this_month',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='daily_reset_date',
            new_name='monthly_reset_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='books_per_day',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='books_per_month',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('parents', 'For Parents'), ('creators', 'For Creators')], default='free', max_length=20),
        ),
    ]
