# Generated by Django 4.2.7 on 2025-10-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_style', models.CharField(choices=[('modern', 'Modern Minimalist'), ('bold', 'Bold Typography'), ('elegant', 'Elegant Professional')], max_length=20)),
                ('image_path', models.CharField(max_length=500)),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('generation_params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='books.book')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['book', '-created_at'], name='covers_cove_book_id_48a69b_idx')],
            },
        ),
    ]
