# Generated by Django 4.2.7 on 2025-10-31 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("covers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cover",
            name="template_style",
            field=models.CharField(
                help_text="Identifier for the dynamic template or trend used to render the cover",
                max_length=80,
            ),
        ),
    ]
