<template>
  <Layout>
    <div class="min-h-screen bg-gray-50 dark:bg-gray-900">

    <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
      <div class="px-4 py-6 sm:px-0">
        <div class="mb-6">
          <h1 class="text-3xl font-bold text-gray-900">Select Your Professional AI Cover</h1>
          <p class="mt-2 text-sm text-gray-600">
            Choose your favorite AI-generated cover design for: <strong>{{ book?.title }}</strong>
          </p>
        </div>

        <div v-if="booksStore.loading" class="text-center py-12">
          <font-awesome-icon :icon="['fas', 'spinner']" spin class="h-12 w-12 text-primary-600" />
          <p class="mt-2 text-gray-600">Loading covers...</p>
        </div>

        <div v-else-if="booksStore.error" class="rounded-md bg-red-50 p-4">
          <div class="flex">
            <font-awesome-icon :icon="['fas', 'exclamation-circle']" class="h-5 w-5 text-red-400" />
            <div class="ml-3">
              <h3 class="text-sm font-medium text-red-800">{{ booksStore.error }}</h3>
            </div>
          </div>
        </div>

        <div v-else-if="book && book.covers.length > 0" class="space-y-6">
          <div class="mb-4 p-4 bg-blue-50 border border-blue-200 rounded-lg">
            <h3 class="text-blue-800 font-medium mb-2">Choose Your Professional AI Cover</h3>
            <p class="text-sm text-blue-600">
              These covers were generated by AI with no template fallbacks. Click on your preferred design below to select it, 
              then click the "Confirm Selection" button to finalize your book.
            </p>
          </div>
          
          <div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
            <div
              v-for="cover in book.covers"
              :key="cover.id"
              class="bg-white overflow-hidden shadow rounded-lg hover:shadow-xl transition-shadow duration-200 cursor-pointer"
              :class="{ 'ring-4 ring-primary-500': selectedCoverId === cover.id }"
              @click="selectedCoverId = cover.id"
            >
              <div class="aspect-[3/4] relative">
                <img
                  :src="cover.image_url"
                  :alt="`Cover ${cover.template_style}`"
                  class="w-full h-full object-cover"
                />
                <div
                  v-if="selectedCoverId === cover.id"
                  class="absolute inset-0 bg-primary-600 bg-opacity-20 flex items-center justify-center"
                >
                  <font-awesome-icon
                    :icon="['fas', 'check-circle']"
                    class="h-16 w-16 text-white"
                  />
                </div>
              </div>
              <div class="p-4">
                <p class="text-sm font-medium text-gray-900 capitalize">
                  {{ cover.template_style }} Style
                </p>
                <p class="text-xs text-gray-500 mt-1">
                  Click to select this cover
                </p>
              </div>
            </div>
          </div>

          <div class="bg-white shadow sm:rounded-lg">
            <div class="px-4 py-5 sm:p-6 flex justify-between items-center">
              <div>
                <h3 class="text-lg leading-6 font-medium text-gray-900">
                  {{ selectedCoverId ? 'Cover selected' : 'No cover selected' }}
                </h3>
                <p class="mt-1 text-sm text-gray-500">
                  {{ selectedCoverId ? 'Click the button to confirm your selection' : 'Click on a cover above to select it' }}
                </p>
              </div>
          <div class="flex space-x-3">
                <router-link
                  :to="`/profile/books/${bookId}`"
                  class="inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50"
                >
                  Cancel
                </router-link>
                <button
                  @click="handleSelectCover"
                  :disabled="!selectedCoverId || booksStore.loading"
                  class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <span v-if="!booksStore.loading">Confirm Selection</span>
                  <span v-else class="flex items-center">
                    <font-awesome-icon :icon="['fas', 'spinner']" spin class="mr-2" />
                    Processing...
                  </span>
                </button>
              </div>
            </div>
          </div>
        </div>

        <div v-else class="text-center py-12">
          <font-awesome-icon :icon="['fas', 'exclamation-circle']" class="h-16 w-16 text-gray-400" />
          <h3 class="mt-2 text-sm font-medium text-gray-900">No AI covers available yet</h3>
          <p class="mt-1 text-sm text-gray-500">
            Professional AI covers are still being generated. Please check back in a moment.
          </p>
          <div class="mt-6">
            <router-link
              :to="`/profile/books/${bookId}`"
              class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700"
            >
              Back to Book Details
            </router-link>
          </div>
        </div>
      </div>
    </div>
  </div>
  </Layout>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { useBooksStore } from '../../stores/books';
import Layout from '../../components/Layout.vue';

interface Props {
  id: string;
}

const props = defineProps<Props>();
const router = useRouter();
const booksStore = useBooksStore();

const selectedCoverId = ref<number | null>(null);
const book = computed(() => booksStore.currentBook);

// Convert string ID to number safely
const bookId = computed(() => {
  const id = parseInt(props.id);
  return isNaN(id) ? 0 : id;
});

onMounted(async () => {
  if (bookId.value === 0) {
    router.push('/profile/books');
    return;
  }
  
  await booksStore.fetchBook(bookId.value);
});

const handleSelectCover = async () => {
  if (!selectedCoverId.value) return;

  booksStore.clearError();
  
  const result = await booksStore.selectCover(bookId.value, {
    cover_id: selectedCoverId.value,
  });

  if (result.success) {
    router.push(`/profile/books/${bookId.value}`);
  }
};
</script>
